function     OUTphreeqSTRING = phreeqcSolvermanyminerals(temperature, pressure, density, Si, K, Na, Al, Mg, pH, reaction_pressure, reaction_temperature, quartzm, quartzm0, ksparm, ksparm0, albitem, albitem0, phlogopitem, phlogopitem0, dtc)
% Creation of the ActiveX server:
iphreeqc = IPhreeqc(); 
iphreeqc = iphreeqc.CreateIPhreeqc(); 
% Specify the database file according to the location on your file system.
iphreeqc.LoadDatabase('.../geothermal.dat'); % Please change this line if you installed this somewhere else

nct = dtc; 

IPCstringCell= {
        'PHASES ', ...
        'K-Feldspar ', ...
        '    KAlSi3O8 +4.0000 H+  =  + 1.0000 Al+++ + 1.0000 K+ + 2.0000 H2O + 3.0000 SiO2 ', ...
        '    log_k           -0.2753 ', ...
        '	-delta_H	   -23.9408	     kJ/mol ', ...
        '   -analytic       -1.0684e+000   1.3111e-002   1.1671e+004   -9.9129e+000   -1.5855e+006 ', ...
        'SOLUTION 1 ', ...
        [' -temp ', num2str(temperature) ], ...   % default, °C
        [' -press ', num2str(pressure), ' atm' ], ...
        [' pH ', num2str(pH), ' charge' ], ...        
        ' pe  4 ', ...
        'redox  pe ', ...
        '-units  mol/L ', ...
        ['-density ', num2str(density) ], ...  % default,solute,kg/L
        [' Si ', num2str(Si) ], ...
        [' K ', num2str(K) ], ...
        [' Na ', num2str(Na) ], ...
        [' Al ', num2str(Al) ], ...
        [' Mg ', num2str(Mg) ], ...
        ' -water 1 ', ...
        ' REACTION_PRESSURE ', ...
        num2str(reaction_pressure) , ...  % default,atm
        ' REACTION_TEMPERATURE ', ...      % default, °C
        num2str(reaction_temperature) , ...
        ' RATES ', ...
        ' K-Feldspar ', ...
        '    -start ', ...
        ' 20 si_kfeld = SI("K-Feldspar") ', ...
        ' 30 if (M <= 0 and si_kfeld < 0) then goto 200 ', ...
        ' 40 SA = PARM(1) * M ', ...
        ' 50 if (M = 0 and si_kfeld > 0) then SA = 1e-05 #nucleation ', ...
        ' 60 k_acid = 10^(-10.06)*EXP(-51.70e+03/8.314*(1.0/TK-1.0/298.15))*ACT("H+")^(0.500) ', ...
        ' 70 k_neut = 10^(-12.41)*EXP(-38.00e+03/8.314*(1.0/TK-1.0/298.15)) ', ...
        ' 80 k_base = 10^(-21.20)*EXP(-94.10e+03/8.314*(1.0/TK-1.0/298.15))*ACT("OH-")^(-0.823) ', ...
        ' 90 k_rateconst = k_acid + k_neut + k_base ', ...
        ' 100 r = k_rateconst * SA * (1-(10^si_kfeld)) ', ...
        ' 190 moles = r * TIME ', ...
        ' 200 SAVE moles ', ...
        '    -end ', ...
        ' KINETICS 1 ', ...
        ' Quartz ', ...
        '    -formula SiO2 1 ', ...
        ['   -m ', num2str(quartzm) ], ...
        ['   -m0 ', num2str(quartzm0) ], ...
        '    -parms 0.98  1.0 ', ...     % calculated before is '-parms 18.977  1.0 ', ...
        '    -tol 1e-08 ', ...
        ' K-Feldspar ', ...
        '    -formula KAlSi3O8 1 ', ...
        ['   -m ', num2str(ksparm) ], ...
        ['   -m0 ', num2str(ksparm0) ], ...
        '    -parms 0.98  1.0 ', ...
        '    -tol 1e-08 ', ...
        ' Albite ', ...
        '    -formula NaAlSi3O8 1 ', ...
        ['   -m ', num2str(albitem) ], ...
        ['   -m0 ', num2str(albitem0) ], ...
        '    -parms 0.98  1.0 ', ...
        '    -tol 1e-08 ', ...
        ' phlogopite ', ...
        '    -formula K1Mg3Al1Si3O12H2 1 ', ...
        ['   -m ', num2str(phlogopitem) ], ...
        ['   -m0 ', num2str(phlogopitem0) ], ...
        '    -parms 0.98  0.0001  ', ...
        '    -tol 1e-08 ', ...
        [' -steps ', num2str(nct), ' in 180 steps '], ...   
        ' -cvode true ', ...
        ' KNOBS ', ...
        ' -convergence_tolerance 1e-10 ', ...
        ' INCREMENTAL_REACTIONS true ', ...
        ' SELECTED_OUTPUT ', ...
        ' -pH true ', ...
        ' -molalities  H+ ', ...  
        ' -totals  Si ', ...      
        ' -totals  K ', ... 
        ' -totals  Na ', ...         
        ' -totals  Al ', ... 
        ' -totals  Mg ', ... 
        ' -saturation_indices  Quartz ', ...    
        ' -saturation_indices  K-Feldspar ', ...
        ' -saturation_indices  ALBITE ', ...
        ' -saturation_indices  PHLOGOPITE ', ...
        ' -Kin  Quartz ', ...    
        ' -Kin  K-Feldspar ', ...
        ' -Kin  Albite ', ...
        ' -Kin  phlogopite ', ...
        ' END'};
    
    IPCstring = sprintf('%s\n', IPCstringCell{:});
    
    % Use the PhreeqC object method RunString with the above defined multiline string.
    
    iphreeqc.RunString( IPCstring );
    
    OUTphreeqSTRING = iphreeqc.GetSelectedOutputValues(1);
    iphreeqc.DestroyIPhreeqc;
  
end